# Generated by Django 3.1.7 on 2021-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_login',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
